compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: 'https://mskelton.dev/yarn-outdated/v3'

yarnPath: .yarn/releases/yarn-4.5.1.cjs

enableTransparentWorkspaces: false


packageExtensions:
  '@fuel-infrastructure/fuel-hyperlane-sdk@*':
    peerDependencies:
      '@ethersproject/abi': '*'
      '@ethersproject/providers': '*'

  '@hyperlane-xyz/core@*':
    peerDependencies:
      '@types/sinon-chai': '*'
