/* Autogenerated file. Do not edit manually. */

/*
  Fuels version: 0.98.0
*/
import { Contract, Interface } from 'fuels';
import type {
  Account,
  Address,
  BN,
  BigNumberish,
  FunctionFragment,
  InvokeFunction,
  Provider,
  StorageSlot,
} from 'fuels';

import type { Enum, Vec } from './common.js';

export enum AccessErrorInput {
  NotOwner = 'NotOwner',
}
export enum AccessErrorOutput {
  NotOwner = 'NotOwner',
}
export type IdentityInput = Enum<{
  Address: AddressInput;
  ContractId: ContractIdInput;
}>;
export type IdentityOutput = Enum<{
  Address: AddressOutput;
  ContractId: ContractIdOutput;
}>;
export enum InitializationErrorInput {
  CannotReinitialized = 'CannotReinitialized',
}
export enum InitializationErrorOutput {
  CannotReinitialized = 'CannotReinitialized',
}
export type StateInput = Enum<{
  Uninitialized: undefined;
  Initialized: IdentityInput;
  Revoked: undefined;
}>;
export type StateOutput = Enum<{
  Uninitialized: void;
  Initialized: IdentityOutput;
  Revoked: void;
}>;

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type ExchangeRateAndGasDataInput = {
  token_exchange_rate: U128Input;
  gas_price: U128Input;
};
export type ExchangeRateAndGasDataOutput = {
  token_exchange_rate: U128Output;
  gas_price: U128Output;
};
export type OwnershipRenouncedInput = { previous_owner: IdentityInput };
export type OwnershipRenouncedOutput = { previous_owner: IdentityOutput };
export type OwnershipSetInput = { new_owner: IdentityInput };
export type OwnershipSetOutput = { new_owner: IdentityOutput };
export type OwnershipTransferredInput = {
  new_owner: IdentityInput;
  previous_owner: IdentityInput;
};
export type OwnershipTransferredOutput = {
  new_owner: IdentityOutput;
  previous_owner: IdentityOutput;
};
export type RemoteGasDataInput = {
  domain: BigNumberish;
  token_exchange_rate: U128Input;
  gas_price: U128Input;
  token_decimals: BigNumberish;
};
export type RemoteGasDataOutput = {
  domain: number;
  token_exchange_rate: U128Output;
  gas_price: U128Output;
  token_decimals: number;
};
export type RemoteGasDataConfigInput = {
  domain: BigNumberish;
  remote_gas_data: RemoteGasDataInput;
};
export type RemoteGasDataConfigOutput = {
  domain: number;
  remote_gas_data: RemoteGasDataOutput;
};
export type U128Input = { upper: BigNumberish; lower: BigNumberish };
export type U128Output = { upper: BN; lower: BN };

const abi = {
  programType: 'contract',
  specVersion: '1',
  encodingVersion: '1',
  concreteTypes: [
    {
      type: '()',
      concreteTypeId:
        '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
    },
    {
      type: 'enum standards::src5::AccessError',
      concreteTypeId:
        '3f702ea3351c9c1ece2b84048006c8034a24cbc2bad2e740d0412b4172951d3d',
      metadataTypeId: 1,
    },
    {
      type: 'enum standards::src5::State',
      concreteTypeId:
        '192bc7098e2fe60635a9918afb563e4e5419d386da2bdbf0d716b4bc8549802c',
      metadataTypeId: 2,
    },
    {
      type: 'enum std::identity::Identity',
      concreteTypeId:
        'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
      metadataTypeId: 3,
    },
    {
      type: 'enum sway_libs::ownership::errors::InitializationError',
      concreteTypeId:
        '1dfe7feadc1d9667a4351761230f948744068a090fe91b1bc6763a90ed5d3893',
      metadataTypeId: 4,
    },
    {
      type: 'struct interfaces::igp::ExchangeRateAndGasData',
      concreteTypeId:
        '1faa08eba9e762b9245ee26834385cebf26f1c4f75a68ec2a2a75c072cc8b864',
      metadataTypeId: 7,
    },
    {
      type: 'struct interfaces::igp::RemoteGasData',
      concreteTypeId:
        'e50775c5f24ae4747aaa1574d1e48ab24b07b3d9fa328970bd7e98436617fe89',
      metadataTypeId: 8,
    },
    {
      type: 'struct interfaces::igp::RemoteGasDataConfig',
      concreteTypeId:
        '2c36f98637c4d192fe28ebd0fd11fbf21a898280e5e8a274df19a024b35e0a24',
      metadataTypeId: 9,
    },
    {
      type: 'struct std::vec::Vec<struct interfaces::igp::RemoteGasDataConfig>',
      concreteTypeId:
        '9ab811124ae9731b223447c9afeffb9db9b20e402faa0ff81c201aa0c678aa1e',
      metadataTypeId: 14,
      typeArguments: [
        '2c36f98637c4d192fe28ebd0fd11fbf21a898280e5e8a274df19a024b35e0a24',
      ],
    },
    {
      type: 'struct sway_libs::ownership::events::OwnershipRenounced',
      concreteTypeId:
        '43c4fa7b3297401afbf300127e59ea913e5c8f0c7ae69abbec789ab0bb872bed',
      metadataTypeId: 15,
    },
    {
      type: 'struct sway_libs::ownership::events::OwnershipSet',
      concreteTypeId:
        'e1ef35033ea9d2956f17c3292dea4a46ce7d61fdf37bbebe03b7b965073f43b5',
      metadataTypeId: 16,
    },
    {
      type: 'struct sway_libs::ownership::events::OwnershipTransferred',
      concreteTypeId:
        'b3fffbcb3158d7c010c31b194b60fb7857adb4ad61bdcf4b8b42958951d9f308',
      metadataTypeId: 17,
    },
    {
      type: 'u32',
      concreteTypeId:
        'd7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc',
    },
  ],
  metadataTypes: [
    {
      type: 'b256',
      metadataTypeId: 0,
    },
    {
      type: 'enum standards::src5::AccessError',
      metadataTypeId: 1,
      components: [
        {
          name: 'NotOwner',
          typeId:
            '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
      ],
    },
    {
      type: 'enum standards::src5::State',
      metadataTypeId: 2,
      components: [
        {
          name: 'Uninitialized',
          typeId:
            '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
        {
          name: 'Initialized',
          typeId: 3,
        },
        {
          name: 'Revoked',
          typeId:
            '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
      ],
    },
    {
      type: 'enum std::identity::Identity',
      metadataTypeId: 3,
      components: [
        {
          name: 'Address',
          typeId: 10,
        },
        {
          name: 'ContractId',
          typeId: 11,
        },
      ],
    },
    {
      type: 'enum sway_libs::ownership::errors::InitializationError',
      metadataTypeId: 4,
      components: [
        {
          name: 'CannotReinitialized',
          typeId:
            '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
      ],
    },
    {
      type: 'generic T',
      metadataTypeId: 5,
    },
    {
      type: 'raw untyped ptr',
      metadataTypeId: 6,
    },
    {
      type: 'struct interfaces::igp::ExchangeRateAndGasData',
      metadataTypeId: 7,
      components: [
        {
          name: 'token_exchange_rate',
          typeId: 12,
        },
        {
          name: 'gas_price',
          typeId: 12,
        },
      ],
    },
    {
      type: 'struct interfaces::igp::RemoteGasData',
      metadataTypeId: 8,
      components: [
        {
          name: 'domain',
          typeId:
            'd7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc',
        },
        {
          name: 'token_exchange_rate',
          typeId: 12,
        },
        {
          name: 'gas_price',
          typeId: 12,
        },
        {
          name: 'token_decimals',
          typeId: 19,
        },
      ],
    },
    {
      type: 'struct interfaces::igp::RemoteGasDataConfig',
      metadataTypeId: 9,
      components: [
        {
          name: 'domain',
          typeId:
            'd7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc',
        },
        {
          name: 'remote_gas_data',
          typeId: 8,
        },
      ],
    },
    {
      type: 'struct std::address::Address',
      metadataTypeId: 10,
      components: [
        {
          name: 'bits',
          typeId: 0,
        },
      ],
    },
    {
      type: 'struct std::contract_id::ContractId',
      metadataTypeId: 11,
      components: [
        {
          name: 'bits',
          typeId: 0,
        },
      ],
    },
    {
      type: 'struct std::u128::U128',
      metadataTypeId: 12,
      components: [
        {
          name: 'upper',
          typeId: 18,
        },
        {
          name: 'lower',
          typeId: 18,
        },
      ],
    },
    {
      type: 'struct std::vec::RawVec',
      metadataTypeId: 13,
      components: [
        {
          name: 'ptr',
          typeId: 6,
        },
        {
          name: 'cap',
          typeId: 18,
        },
      ],
      typeParameters: [5],
    },
    {
      type: 'struct std::vec::Vec',
      metadataTypeId: 14,
      components: [
        {
          name: 'buf',
          typeId: 13,
          typeArguments: [
            {
              name: '',
              typeId: 5,
            },
          ],
        },
        {
          name: 'len',
          typeId: 18,
        },
      ],
      typeParameters: [5],
    },
    {
      type: 'struct sway_libs::ownership::events::OwnershipRenounced',
      metadataTypeId: 15,
      components: [
        {
          name: 'previous_owner',
          typeId: 3,
        },
      ],
    },
    {
      type: 'struct sway_libs::ownership::events::OwnershipSet',
      metadataTypeId: 16,
      components: [
        {
          name: 'new_owner',
          typeId: 3,
        },
      ],
    },
    {
      type: 'struct sway_libs::ownership::events::OwnershipTransferred',
      metadataTypeId: 17,
      components: [
        {
          name: 'new_owner',
          typeId: 3,
        },
        {
          name: 'previous_owner',
          typeId: 3,
        },
      ],
    },
    {
      type: 'u64',
      metadataTypeId: 18,
    },
    {
      type: 'u8',
      metadataTypeId: 19,
    },
  ],
  functions: [
    {
      inputs: [
        {
          name: 'domain',
          concreteTypeId:
            'd7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc',
        },
      ],
      name: 'get_exchange_rate_and_gas_price',
      output:
        '1faa08eba9e762b9245ee26834385cebf26f1c4f75a68ec2a2a75c072cc8b864',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [
            ' Gets the token exchange rate and gas price for a given domain.',
          ],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' ### Arguments'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [
            ' * `domain`: [u32] - The domain to get the gas data for.',
          ],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' ### Returns'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [
            ' * [ExchangeRateAndGasData] - The exchange rate and gas price for the remote domain.',
          ],
        },
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'domain',
          concreteTypeId:
            'd7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc',
        },
      ],
      name: 'get_remote_gas_data',
      output:
        'e50775c5f24ae4747aaa1574d1e48ab24b07b3d9fa328970bd7e98436617fe89',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [' Gets the gas data from storage.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' ### Arguments'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [
            ' * `domain`: [u32] - The domain to get the gas data for.',
          ],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' ### Returns'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [
            ' * [RemoteGasData] - The gas data for the remote domain.',
          ],
        },
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'configs',
          concreteTypeId:
            '9ab811124ae9731b223447c9afeffb9db9b20e402faa0ff81c201aa0c678aa1e',
        },
      ],
      name: 'set_remote_gas_data_configs',
      output:
        '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [
            ' Sets the gas data for a given domain. Only callable by the owner.',
          ],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' ### Arguments'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [
            ' * `configs`: [Vec]<[RemoteGasDataConfig]> - The remote gas data configs to set.',
          ],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' ### Reverts'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * If the caller is not the owner.'],
        },
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'new_owner',
          concreteTypeId:
            'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
        },
      ],
      name: 'initialize_ownership',
      output:
        '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [],
      name: 'only_owner',
      output:
        '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [],
      name: 'owner',
      output:
        '192bc7098e2fe60635a9918afb563e4e5419d386da2bdbf0d716b4bc8549802c',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [],
      name: 'renounce_ownership',
      output:
        '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'new_owner',
          concreteTypeId:
            'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
        },
      ],
      name: 'transfer_ownership',
      output:
        '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['write'],
        },
      ],
    },
  ],
  loggedTypes: [
    {
      logId: '4571204900286667806',
      concreteTypeId:
        '3f702ea3351c9c1ece2b84048006c8034a24cbc2bad2e740d0412b4172951d3d',
    },
    {
      logId: '2161305517876418151',
      concreteTypeId:
        '1dfe7feadc1d9667a4351761230f948744068a090fe91b1bc6763a90ed5d3893',
    },
    {
      logId: '16280289466020123285',
      concreteTypeId:
        'e1ef35033ea9d2956f17c3292dea4a46ce7d61fdf37bbebe03b7b965073f43b5',
    },
    {
      logId: '4883303303013154842',
      concreteTypeId:
        '43c4fa7b3297401afbf300127e59ea913e5c8f0c7ae69abbec789ab0bb872bed',
    },
    {
      logId: '12970362301975156672',
      concreteTypeId:
        'b3fffbcb3158d7c010c31b194b60fb7857adb4ad61bdcf4b8b42958951d9f308',
    },
  ],
  messagesTypes: [],
  configurables: [],
};

const storageSlots: StorageSlot[] = [];

export class GasOracleInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    get_exchange_rate_and_gas_price: FunctionFragment;
    get_remote_gas_data: FunctionFragment;
    set_remote_gas_data_configs: FunctionFragment;
    initialize_ownership: FunctionFragment;
    only_owner: FunctionFragment;
    owner: FunctionFragment;
    renounce_ownership: FunctionFragment;
    transfer_ownership: FunctionFragment;
  };
}

export class GasOracle extends Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: GasOracleInterface;
  declare functions: {
    get_exchange_rate_and_gas_price: InvokeFunction<
      [domain: BigNumberish],
      ExchangeRateAndGasDataOutput
    >;
    get_remote_gas_data: InvokeFunction<
      [domain: BigNumberish],
      RemoteGasDataOutput
    >;
    set_remote_gas_data_configs: InvokeFunction<
      [configs: Vec<RemoteGasDataConfigInput>],
      void
    >;
    initialize_ownership: InvokeFunction<[new_owner: IdentityInput], void>;
    only_owner: InvokeFunction<[], void>;
    owner: InvokeFunction<[], StateOutput>;
    renounce_ownership: InvokeFunction<[], void>;
    transfer_ownership: InvokeFunction<[new_owner: IdentityInput], void>;
  };

  constructor(id: string | Address, accountOrProvider: Account | Provider) {
    super(id, abi, accountOrProvider);
  }
}
